config/routes.rb
FinalProject::Application.routes.draw do
  resources :articles, :products, :users, :sessions, :categories, :comments

  namespace :admin do
    resources :categories
  end
  
  root :to => "home_pages#index"
  get "logout" => "sessions#destroy", :as => "logout"
  get "my_articles" => "articles#my_articles", :as => "my_articles"
  get "my_products" => "products#my_products", :as => "my_products"
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :body, :title, :user_id
  
  validates :body, :presence => true,
                   :length => {:minimum => 5, :maximum => 2048}
  validates :title, :presence => true,
                    :length => {:maximum => 255}
  validates :user_id, :presence => true
  
  belongs_to :user
  has_many :comments
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :require_login, :only => [:new, :create, :edit, :update, :destroy, :my_articles]
  before_filter :check_self_owner, :only => [:edit, :update, :destroy]
  
  #prevent user editing article owned by other user
  def check_self_owner
    if Integer(Article.find(params[:id]).user_id) != session[:user_id]
      flash[:session] = "You are not authorized"
      redirect_to root_path
    end
  end
  
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end
  
  #show only article owned by user
  def my_articles
    @articles = Article.find_all_by_user_id(session[:user_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comments = Comment.find_all_by_article_id(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    params[:article][:user_id] = session[:user_id]
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to my_articles_path, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    params[:article][:user_id] = session[:user_id]
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to my_articles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_comments.html.erb
  <% if @comments.size > 0 %>
  <% @comments.each do |comment| %>
    <%= comment.comment %>
    <br />
  <% end %>
  <%else%>
  No comment yet
  <%end%>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/_latest_articles.html.erb
<% content_for :content do %>
  <h1>Latest Articles</h1>
  <br />
  <% if @articles.nil? %>
  <h4>No Article Found</h4>
  <% else %>
    <% @articles.each do |article| %>
        <p>
          <%= truncate(article.body,:length => 100) %><br /><br />
          <%= link_to 'See detail', article %>
        </p>
        <br /><br />
    <% end %>
  <% end %>
<%end%>

app/views/articles/edit.html.erb
<% content_for :content do %>
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>
<%end%>

app/views/articles/index.html.erb
<% content_for :content do %>
  <h1>Listing articles</h1>
  <br />
  <% if @articles.nil? %>
  <br />
  <h4>No Article Found</h4>
  <% else %>
    <% @articles.each do |article| %>
        <p>
          Title : <%= article.title %><br />
          Body : <%= truncate(article.body,:length => 100) %><br /><br />
          <%= link_to 'See detail', article %>
        </p>
        <br /><br />
    <% end %>
  <% end %>
<%end%>

app/views/articles/my_articles.html.erb
<% content_for :content do %>
<h1>My Shared Articles</h1><br />
<%= link_to 'Share New Article', new_article_path %>
<br /> <br />
<% if @articles.nil? %>
<br />
<h4>No Article Found</h4>
<% else %>
  <% @articles.each do |article| %>
      <p>Title : <%= article.title %></p>
      <p>Body : <%= truncate(article.body,:length => 100) %></p>
      <%= link_to 'See detail', article %> | 
      <%= link_to 'Edit', edit_article_path(article) %> | 
      <%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?' } %>
      <br /><br />
  <% end %>
<% end %>
<%end%>

app/views/articles/new.html.erb
<% content_for :content do %>
<h1>New article</h1>

<%= render 'form' %>

<%end%>

app/views/articles/show.html.erb
<% content_for :content do %>
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @article.title %>
</p>

<p>
  <b>Body:</b>
  <%= @article.body %>
</p>

<p>
  <b>Author:</b>
  <%= User.find(@article.user_id).name %>
</p>
<br /><br />

<h4>Comments</h4>
<div id="comments">
  <%= render :partial => "comments", :locals => {:comments => @comments}  %>
</div>

<br /><br />
<% if session[:user_id] %>
  <p id="ajax-notice" style="color:#ff0000"></p>
  <h4>Add New Comment</h4>
  <% unless(current_user.nil?)%>
     <%= form_for @comment, :remote => true, :url => comments_path do |f| -%>
        <%= f.text_area :comment %>
        <%= f.hidden_field :article_id, :value => @article.id %>
        <br />
        <%= submit_tag "comment" %>
    <% end -%>
  <% end %>
<% else %>
  <h2>Please login first, to post comment</h2>
<% end %>
<br />
<%= link_to 'Back', articles_path %>
<%end%>