config/routes.rb
FinalProject::Application.routes.draw do
  resources :articles, :products, :users, :sessions, :categories, :comments

  namespace :admin do
    resources :categories
  end
  
  root :to => "home_pages#index"
  get "logout" => "sessions#destroy", :as => "logout"
  get "my_articles" => "articles#my_articles", :as => "my_articles"
  get "my_products" => "products#my_products", :as => "my_products"
  

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :parent_id
  
  has_many :products
  
  validates :name, :presence => true,
                   :length => {:maximum => 255},
                   :uniqueness => true
                  
  
  #get parent_name of category
  def parent_name
    result=""
    begin
      result = Category.find(self.parent_id).name
    rescue
    end
    return result
  end
  
  #get all child category with parent_id of
  def self.get_child(parent_id)
    return Category.where("parent_id = #{parent_id}")
  end
  
  #get all parent category
  def self.get_parent
    return Category.where("parent_id IS NULL")
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  before_filter :require_admin_login
  
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new
    @parent_categories = Category.where("parent_id IS NULL")

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
    @parent_categories = Category.where("parent_id IS NULL")
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to [:admin, @category], notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: :new, notice: 'Category create failed.' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to [:admin, @category], notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to admin_categories_url }
      format.json { head :no_content }
    end
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :check_admin, :on => :index
  
  #check is user an admin, if admin redirect to admin namespace
  def check_admin
    if current_user.is_admin?
      redirect_to admin_categories_path
    else
      flash[:session] = "Forbidden access"
      redirect_to root_path
    end
  end
  
  def index; end
  
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for([:admin, @category]) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field"> <%= f.label "Parent Category" %>
    <select id="category_parent_id" name="category[parent_id]">
      <option value="">No Parent</option>
      <% unless @parent_categories.nil? %>
        <% @parent_categories.each do |parent| %>
          <option value="<%= parent.id %>" <%if parent.id == @category.parent_id then %> selected="selected" <%end%>><%= parent.name %></option>
        <% end %>
      <% end %>
    </select>
  </div>
  <div class="actions">
    <%= f.submit %> <%= link_to 'Back', categories_path %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<% content_for :content do %>
<h1>Editing category</h1>

<%= render 'form' %>

<% end %>

app/views/admin/categories/index.html.erb
<% content_for :content do %>
  <h1>Listing categories</h1>
  <br />
  <%= link_to 'New Category', new_admin_category_path %>
  <br /><br />
  <table>
    <tr>
      <th>Name</th>
      <th>Parent Category</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  
  <% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
      <td><%= category.parent_name %></td>
      <td><%= link_to 'Show', [:admin, category] %> | 
      <%= link_to 'Edit', edit_admin_category_path(category) %> | 
      <%= link_to 'Destroy', [:admin, category], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </table>
<% end %>

app/views/admin/categories/new.html.erb
<% content_for :content do %>
  <h1>New category</h1>
  <%= render 'form' %>
<% end %>

app/views/admin/categories/show.html.erb
<% content_for :content do %>
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Parent:</b>
  <%= @parent_categories %>
</p>


<%= link_to 'Edit', edit_admin_category_path(@category) %> |
<%= link_to 'Back', admin_categories_path %>
<% end %>