config/routes.rb
FinalProject::Application.routes.draw do
  resources :articles, :products, :users, :sessions, :categories, :comments

  namespace :admin do
    resources :categories
  end
  
  root :to => "home_pages#index"
  get "logout" => "sessions#destroy", :as => "logout"
  get "my_articles" => "articles#my_articles", :as => "my_articles"
  get "my_products" => "products#my_products", :as => "my_products"
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FinalProject</title>
  <%= stylesheet_link_tag "reset", :media => "all" %>
  <%= stylesheet_link_tag "960", :media => "all" %>
  <%= stylesheet_link_tag "layout", :media => "all" %>
  <%= javascript_include_tag "application" %>
  
   <!--[if IE]>
      <%= stylesheet_link_tag "ie-fix", :media => "all" %>
      <%= javascript_include_tag "html5" %>
      <%= javascript_include_tag "selectivizr" %>
   <![endif]-->
  
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container_12">
  	
  	<header>
      <h1 id="page-title" class="grid_12">Welcome to My Store</h1>
      <div class="grid_12">
        <nav>
          <ul id="main-menu">
            <% unless session[:user_id].nil? %>
              <li><a href="<%= url_for root_path %>">Home</a></li>
            <%else%>
              <li><a href="<%= url_for new_user_path %>">Signup</a></li>
            <%end%>
            <li><a href="<%= url_for products_path %>">Products</a></li>
            <li><a href="<%= url_for articles_path %>">Articles</a></li>
            <%unless current_user.nil? 
               if current_user.is_admin?  %>
                 <li><a href="<%= url_for categories_path %>">Categories</a></li>
            <% end
             end%>
          </ul>
        </nav>
      </div>
      <div class="clear"></div>
    </header>
    <br />
    <aside id="left_panel" class="grid_4">
      <div class="box"><%= render :partial => "./sessions/login_box" %></div>
      <% unless session[:user_id].nil? %>
        <div class="box"><%= render :partial => "./categories/category_tree_menu" %></div>
      <% end %>
      <%= yield :left_panel %>
    </aside>
    
    <div id="content" class="grid_8">
      <div id="wrapper">
      <%= yield :content %>
      </div>
    </div>
    
    <div class="clear"></div>
    
    <footer class="grid_12">
      <%= yield :footer %>
      <br /><br /><br /><br />
    </footer>
    
    <div class="clear"></div>
  </div>
</body>
</html>